---
- hosts: "localhost"
  connection: "local"
  roles:
    - role: "avinetworks.avisdk"
  vars_files:
    - "vars.yaml"

  tasks:
    - name: "Check for Initial Setup"
      uri:
        url: '{{"https://" + avi_credentials.controller + "/api/initial-data?include-name"}}'
        method: "get"
        status_code: 200
        timeout: 10
        validate_certs: "no"
      register: avi_initial_data

    - name: "Bootstrap Controller"
      avi_api_session:
        avi_credentials:
          controller: "{{ avi_credentials.controller }}"
          username: "admin"
          password: "{{ avi_default_password }}"
          api_version: "{{ avi_credentials.api_version }}"
        http_method: "put"
        path: '{{ "useraccount" }}'
        data:
          old_password: "{{ avi_default_password }}"
          password: "{{ avi_admin_password }}"
      when: avi_initial_data.json.user_initial_setup

    - name: "Configure System"
      avi_systemconfiguration:
        avi_credentials: "{{ avi_credentials | default(omit) }}"
        api_context: "{{ avi_api_context | default(omit) }}"
        dns_configuration: "{{ system_configuration.dns_configuration | default(omit)}}"
        ntp_configuration: "{{ system_configuration.ntp_configuration | default(omit)}}"
        global_tenant_config: "{{ system_configuration.global_tenant_config | default(omit)}}"
        welcome_workflow_complete: true
